In [3]:
import numpy as np
from scipy import stats
from scipy import io as spio
from scipy import misc
from scipy import special
from scipy import integrate
from scipy import linalg
from scipy.spatial.distance import pdist, squareform
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import dijkstra
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
import pandas

In [2]:
%matplotlib inlineC, S = np.cos(X), np.sin(X)


UsageError: unrecognized arguments: S = np.cos(X), np.sin(X)

In [3]:
plt.show()


In [4]:
X = np.linspace(-np.pi, np.pi, 256, endpoint=True)

In [5]:
C, S = np.cos(X), np.sin(X)


In [6]:
X

array([-3.14159265, -3.11695271, -3.09231277, -3.06767283, -3.04303288,
       -3.01839294, -2.993753  , -2.96911306, -2.94447311, -2.91983317,
       -2.89519323, -2.87055329, -2.84591335, -2.8212734 , -2.79663346,
       -2.77199352, -2.74735358, -2.72271363, -2.69807369, -2.67343375,
       -2.64879381, -2.62415386, -2.59951392, -2.57487398, -2.55023404,
       -2.52559409, -2.50095415, -2.47631421, -2.45167427, -2.42703432,
       -2.40239438, -2.37775444, -2.3531145 , -2.32847456, -2.30383461,
       -2.27919467, -2.25455473, -2.22991479, -2.20527484, -2.1806349 ,
       -2.15599496, -2.13135502, -2.10671507, -2.08207513, -2.05743519,
       -2.03279525, -2.0081553 , -1.98351536, -1.95887542, -1.93423548,
       -1.90959553, -1.88495559, -1.86031565, -1.83567571, -1.81103577,
       -1.78639582, -1.76175588, -1.73711594, -1.712476  , -1.68783605,
       -1.66319611, -1.63855617, -1.61391623, -1.58927628, -1.56463634,
       -1.5399964 , -1.51535646, -1.49071651, -1.46607657, -1.44

In [7]:
plt.plot(X,C)
plt.plot(X, S)

In [8]:
plt.show()


In [9]:
data = np.load('pop.npy')
data

array([[ 60,  60,  60],
       [ 60,  60,  60],
       [ 60,  60,  60],
       ..., 
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [10]:
run matplotlib_1.py


In [11]:
plt.plot(data)

In [12]:
plt.figure(figsize=(100, 60), dpi=80)


In [13]:
plt.plot(data)

In [14]:
n = 1024
X = np.random.normal(0,1,n)
Y = np.random.normal(0,1,n)
X
Y

array([-0.25580799,  0.30146998, -0.9857509 , ..., -1.53472661,
        0.14197963, -1.79809603])

In [15]:
X

array([-1.13093104, -1.99440461, -0.94642752, ..., -0.12341314,
       -0.05005049, -0.08364682])

In [16]:
Y

array([-0.25580799,  0.30146998, -0.9857509 , ..., -1.53472661,
        0.14197963, -1.79809603])

In [17]:
X = data[:,0]
X

array([ 60,  60,  60, ..., 100, 100, 100])

In [18]:
Y = data[:,1]
Y

array([ 60,  60,  60, ..., 100, 100, 100])

In [19]:
Z = data[:, 2]
Z

array([ 60,  60,  60, ..., 100, 100, 100])

In [20]:
plt.scatter(X, Y)

In [21]:
man plt.scatter


In [22]:
fig = plt.figure()
ax = Axes3D(fig)


In [23]:
ax.scatter(X,Y,zdir='z',Z,s=20,c='blue',depthshade=True)

SyntaxError: non-keyword arg after keyword arg (<ipython-input-23-518dcf448638>, line 1)

In [ ]:
data1 = pandas.read_csv("FT_ALL.csv",sep=",",na_values='/')

In [ ]:
data1


In [ ]:
def drumhead_height(n, k, distance, angle, t):
   kth_zero = special.jn_zeros(n, k)[-1]
   return np.cos(t) * np.cos(n*angle) * special.jn(n, distance*kth_zero)
theta  = np.r_[0:2*np.pi:50j]
radius = np.r_[0:1:50j]
x = np.array([r * np.cos(theta) for r in radius])
y = np.array([r * np.sin(theta) for r in radius])
z = np.array([drumhead_height(1, 1, r, theta, 0.5) for r in radius])

In [ ]:
fig = plt.figure()
ax = Axes3D(fig)

In [ ]:
ax.plot_surface(x, y, z, rstride=1, cstride=1, cmap=cm.jet)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.show()


In [ ]:
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print reslut

In [ ]:
I = sqrt(2/pi) * ( 18.0 / 27 * sqrt(2) * cos(4.5) - 4.0 / 27 * sqrt(2) * sin(4.5) + sqrt(2*pi) * special.fresnel(3/sqrt(pi))[0])

In [ ]:
print I

In [ ]:
print abs(result[0]-I)

In [ ]:
print reslut

In [2]:
A = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])

array([[1, 2],
       [3, 4]])

In [4]:
linalg.inv(A).dot(b)

array([[-4. ],
       [ 4.5]])

In [5]:
A.dot(linalg.inv(A).dot(b))-b

array([[  0.00000000e+00],
       [  1.77635684e-15]])

In [6]:
np.linalg.solve(A,b)

array([[-4. ],
       [ 4.5]])

In [7]:
A.dot(np.linalg.solve(A,b))-b

array([[ 0.],
       [ 0.]])

In [8]:
linalg.det(A)

-2.0

In [9]:
linalg.norm(A)

5.4772255750516612

In [10]:
c1, c2 = 5.0, 2.0
i = np.r_[1:11]
xi = 0.1*i
yi = c1*np.exp(-xi) + c2*xi
zi = yi + 0.05 * np.max(yi) * np.random.randn(len(yi))

In [11]:
A = np.c_[np.exp(-xi)[:, np.newaxis], xi[:, np.newaxis]]
c, resid, rank, sigma = linalg.lstsq(A, zi)

In [12]:
xi2 = np.r_[0.1:1.0:100j]
yi2 = c[0]*np.exp(-xi2) + c[1]*xi2

In [13]:
plt.plot(xi,zi,'x',xi2,yi2)
plt.axis([0,1.1,3.0,5.5])
plt.xlabel('$x_i$')
plt.title('Data fitting with linalg.lstsq')
plt.show()

In [14]:
word_list = open('/usr/share/dict/words').readlines()
word_list = map(str.strip, word_list)

In [20]:
word_list = [word for word in word_list if len(word) == 3]
word_list = [word for word in word_list if word[0].islower()]
word_list = [word for word in word_list if word.isalpha()]
word_list = map(str.lower, word_list)
len(word_list)

1135

In [22]:
word_list = np.asarray(word_list)
word_list.dtype
word_list.sort()

In [23]:
word_bytes = np.ndarray((word_list.size, word_list.itemsize),
                        dtype='int8',
                        buffer=word_list.data)
word_bytes.shape

(1135, 3)

In [24]:
word_bytes

array([[ 97,  97, 108],
       [ 97,  97, 109],
       [ 97,  98,  97],
       ..., 
       [122, 105, 112],
       [122, 111,  97],
       [122, 111, 111]], dtype=int8)

In [26]:
hamming_dist = pdist(word_bytes, metric='hamming')
graph = csr_matrix(squareform(hamming_dist < 1.5 / word_list.itemsize))

In [27]:
i1 = word_list.searchsorted('ape')
i2 = word_list.searchsorted('man')
word_list[i1]

'ape'

In [30]:
distances, predecessors = dijkstra(graph, indices=i1, return_predecessors=True)
print distances[i2]

5.0


In [38]:
path = []
i = i2
while i != i1:
    path.append(word_list[i])
    i = predecessors[i]
path.append(word_list[i1])
print path[::-1]

[array([], 
      dtype='|S3')]


In [39]:
from scipy.sparse.csgraph import connected_components
N_components, component_list = connected_components(graph)
print N_components

4


In [40]:
[np.sum(component_list == i) for i in range(15)]

[1132, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [41]:
[list(word_list[np.where(component_list == i)]) for i in range(1, 15)]

[['edh'], ['its'], ['nth'], [], [], [], [], [], [], [], [], [], [], []]

In [42]:
distances, predecessors = dijkstra(graph, return_predecessors=True)
np.max(distances[~np.isinf(distances)])

8.0

In [43]:
i1, i2 = np.where(distances == 13)
zip(word_list[i1], word_list[i2])

[]

In [44]:
path = []
i = i2[0]
while i != i1[0]:
    path.append(word_list[i])
    i = predecessors[i1[0], i]
path.append(word_list[i1[0]])
print path[::-1]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [4]:
from scipy.spatial import Delaunay
points = np.array([[0, 0], [0, 1.1], [1, 0], [1, 1]])
tri = Delaunay(points)
points

array([[ 0. ,  0. ],
       [ 0. ,  1.1],
       [ 1. ,  0. ],
       [ 1. ,  1. ]])

In [5]:
plt.triplot(points[:,0], points[:,1], tri.simplices.copy())
plt.plot(points[:,0], points[:,1], 'o')

In [7]:
for j, p in enumerate(points):
    plt.text(p[0]-0.03, p[1]+0.03, j, ha='right') # label the points
for j, s in enumerate(tri.simplices):
    p = points[s].mean(axis=0)
    plt.text(p[0], p[1], '#%d' % j, ha='center') # label triangles
plt.xlim(-0.5, 1.5); plt.ylim(-0.5, 1.5)
plt.show()

In [8]:
i = 1
tri.simplices[i,:]

points[tri.simplices[i,:]]

array([[ 1. ,  1. ],
       [ 0. ,  1.1],
       [ 0. ,  0. ]])

In [9]:
tri.neighbors[i]

array([-1,  0, -1], dtype=int32)

In [10]:
points[tri.simplices[i, 1]]

array([ 0. ,  1.1])

In [11]:
points = np.array([[0, 0], [0, 1], [1, 0], [1, 1], [1, 1]])
tri = Delaunay(points)
np.unique(tri.simplices.ravel())

array([0, 1, 2, 3], dtype=int32)

In [12]:
tri.coplanar

array([[4, 0, 3]], dtype=int32)

In [13]:
tri = Delaunay(points, qhull_options="QJ Pp")
points[tri.simplices]

array([[[1, 0],
        [1, 1],
        [0, 0]],

       [[1, 1],
        [1, 1],
        [1, 0]],

       [[1, 1],
        [0, 1],
        [0, 0]],

       [[0, 1],
        [1, 1],
        [1, 1]]])

In [14]:
from scipy.spatial import ConvexHull
points = np.random.rand(30, 2)   # 30 random points in 2-D
hull = ConvexHull(points)
hull

In [15]:
plt.plot(points[:,0], points[:,1], 'o')
for simplex in hull.simplices:
    plt.plot(points[simplex,0], points[simplex,1], 'k-')
plt.show()

In [16]:
from scipy.spatial import KDTree
points = np.array([[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2],
                   [2, 0], [2, 1], [2, 2]])
tree = KDTree(points)
tree.query([0.1, 0.1])

(0.14142135623730953, 0)

In [20]:
x = np.linspace(-0.5, 2.5, 31)
y = np.linspace(-0.5, 2.5, 33)
xx, yy = np.meshgrid(x, y)
xy = np.c_[xx.ravel(), yy.ravel()]

plt.pcolor(x, y, tree.query(xy)[1].reshape(33, 31))
plt.plot(points[:,0], points[:,1], 'ko')
plt.show()

In [21]:
from scipy.spatial import Voronoi
vor = Voronoi(points)
vor.vertices

array([[ 0.5,  0.5],
       [ 1.5,  0.5],
       [ 0.5,  1.5],
       [ 1.5,  1.5]])

In [22]:
vor.regions

[[],
 [-1, 0],
 [-1, 1],
 [1, -1, 0],
 [3, -1, 2],
 [-1, 3],
 [-1, 2],
 [3, 2, 0, 1],
 [2, -1, 0],
 [3, -1, 1]]

In [23]:
vor.ridge_vertices

[[-1, 0],
 [-1, 0],
 [-1, 1],
 [-1, 1],
 [0, 1],
 [-1, 3],
 [-1, 2],
 [2, 3],
 [-1, 3],
 [-1, 2],
 [0, 2],
 [1, 3]]

In [24]:
vor.ridge_points

array([[0, 1],
       [0, 3],
       [6, 3],
       [6, 7],
       [3, 4],
       [5, 8],
       [5, 2],
       [5, 4],
       [8, 7],
       [2, 1],
       [4, 1],
       [4, 7]], dtype=int32)

In [25]:
plt.plot(points[:,0], points[:,1], 'o')
plt.plot(vor.vertices[:,0], vor.vertices[:,1], '*')
plt.xlim(-1, 3); plt.ylim(-1, 3)

(-1, 3)

In [26]:
for simplex in vor.ridge_vertices:
    simplex = np.asarray(simplex)
    if np.all(simplex >= 0):
        plt.plot(vor.vertices[simplex,0], vor.vertices[simplex,1], 'k-')